databaseChangeLog:
  - changeSet:
      id: 3.18.0
      author: GraviteeSource Team
      changes:
        - addColumn:
            tableName: ${gravitee_prefix}alert_triggers
            columns:
              - column:
                  name: environment_id
                  type: nvarchar(64)

        # Upgrader FWK
        - createTable:
            tableName: ${gravitee_prefix}upgrader_record
            columns:
              - column: { name: id, type: nvarchar(1024), constraints: { nullable: false } }
              - column: { name: applied_at, type: timestamp(6), constraints: { nullable: false } }

        - addPrimaryKey:
            constraintName: pk_${gravitee_prefix}upgrader_record
            columnNames: id
            tableName: ${gravitee_prefix}upgrader_record