version: 2.1
orbs:
    snyk: snyk/snyk@1.1.2
commands:
    docker-scan:
        steps:
            - snyk/scan:
                organization: gravitee.io
                monitor-on-build: true
                severity-threshold: critical
                docker-image-name: ${IMAGE_TAG}
                fail-on-issues: false
                project: no
                
jobs:
    publish_prod_docker_images:
        docker:
            - image: cimg/base:stable
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Build & Publish Web UI Docker Image to Azure Registry
                command: |
                  export IMAGE_TAG=graviteeio/apim-management-ui:3.17.1-ee
                  echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV                  
            - docker-scan

workflows:
    pull_requests:
        jobs:
            - publish_prod_docker_images
