version: 2.1
orbs:
    snyk: snyk/snyk@1.1.2
commands:
    docker-scan:
        parameters:
            docker-image-name:
                type: string
                default: ""
                description: The name of the docker image to scan (without the version)
            version:
                type: string
                default: ""
                description: Version of the docker image to scan    
        steps:
          - run:
              name: install-nodejs
              command: sudo apt install nodejs
          - run:
              name: install-snyk
              command: sudo npm install snyk -g                          
          - run: # run snyk help - test snyk is installed and working
              name: snyk-help
              command: snyk --help
          - run: # run snyk auth - authenticate snyk use environment variables to add token
              name: snyk auth
              command: snyk auth $SNYK_TOKEN
          - run: # run snyk test - run snyk test
              name: snyk test
              command: |
                snyk config set disableSuggestions=true
                snyk container monitor << parameters.docker-image-name >>:<< parameters.version >> --project-name=<< parameters.version >> --app-vulns -d
                #snyk container test graviteeio/apim-management-api:3-ee --app-vulns        
           # - snyk/scan:
           #     organization: gravitee.io
           #     monitor-on-build: true
           #     severity-threshold: high
           #     docker-image-name: << parameters.docker-image-name >>:<< parameters.version >>
           #     fail-on-issues: false
           #     project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-container'
        
    publish_prod_docker_images:
        parameters:
            dry_run:
                type: boolean
                default: true
            enterprise_edition:
                default: false
                type: boolean
            graviteeio_version:
                default: "3"
                type: string              
        docker:
            - image: cimg/base:stable
        steps:
            - when:
                  condition:
                      equal: [false, << parameters.dry_run >>]
                  steps:
                      - docker-scan:
                            docker-image-name: graviteeio/apim-management-api
                            version: << parameters.graviteeio_version >><<# parameters.enterprise_edition >>-ee<</ parameters.enterprise_edition >>
                            #echo << parameters.version >>
            
workflows:
    pull_requests:
        jobs:
            - publish_prod_docker_images:
                 dry_run: false
                 graviteeio_version: "3.15"
                 enterprise_edition: true
           
