version: 2.1
orbs:
    slack: circleci/slack@4.8.1
commands:            
    notify-snyk-result:
      steps:
          - slack/notify:
                channel: 'devsecops'
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "```${SLACK_MESSAGE}```"
                       },
                       "accessory": {
                         "type": "button",
                         "text": {
                           "type": "plain_text",
                           "text": "Click here for scan details",
                           "emoji": true
                         },
                         "value": "click_me_123",
                         "url": "${CIRCLE_BUILD_URL}",
                         "action_id": "button-action"                    
                        }
                      }
                    ]
                  }
                event: always

jobs:       
    publish_prod_docker_images:          
        docker:
            #- image: cimg/base:stable
            - image: cimg/openjdk:17.0.1    
        steps:
            - run:
                name: snyk scan 1
                command: |  
                  curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
                  sudo apt install nodejs
                  sudo npm install snyk -g                          
                  snyk auth $SNYK_TOKEN
                  SLACK_MESSAGE="test image name 1"
                  echo $SLACK_MESSAGE
                  echo "export SLACK_MESSAGE='${SLACK_MESSAGE}'" >> $BASH_ENV  
                  snyk container test graviteeio/apim-management-ui:3.10.14 --app-vulns -d
            - notify-snyk-result
            - run:
                name: snyk scan 2
                when: always                
                command: |
                  SLACK_MESSAGE="test image name 2"
                  echo $SLACK_MESSAGE
                  echo "export SLACK_MESSAGE='${SLACK_MESSAGE}'" >> $BASH_ENV  
                  snyk container test graviteeio/apim-management-ui:3.10.14 --app-vulns -d
            - notify-snyk-result  
            - run:
                name: snyk scan 3  
                when: always
                command: |
                  SLACK_MESSAGE="test image name 2" 
                  exit 0
            
    publish_prod_docker_images1:          
        docker:
            - image: cimg/openjdk:17.0.1    
        steps:
            - run:
                name: snyk scan 4
                command: |     
                  curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
                  sudo apt install nodejs
                  sudo npm install snyk -g                
workflows:
    pull_requests:
        jobs:
            - publish_prod_docker_images
            - publish_prod_docker_images1:
                requires:
                  - publish_prod_docker_images
            

           
