version: 2.1

slack-fail-post-step: &slack-fail-post-step
  post-steps:
    - slack/status:
        fail_only: true

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: cimg/base:stable
      
    steps:
      - run:
          name: Success
          command: |
            exit 0
  last-job:
    docker:
      - image: cimg/base:stable
      
    steps:
      - run:
          name: Success
          command: |
            exit 0
  
workflows:
  version: 2
  workflow:
    jobs:
      - build: *slack-fail-post-step
      - last-job:
          requires:
            - build
          post-steps:
            - slack/status
