version: 2.1
orbs:
    snyk: snyk/snyk@1.1.2
parameters:
    version:
      type: string
      description: version of the database to test
      default: "xyz"   

commands:
    docker-scan:
        steps:
            - snyk/scan:
                organization: gravitee.io
                monitor-on-build: true
                severity-threshold: critical
                docker-image-name: ${IMAGE}
                fail-on-issues: false
                project: ${IMAGE_TAG}
               
jobs:
    publish_prod_docker_images:
        docker:
            - image: cimg/base:stable
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Build & Publish Web UI Docker Image to Azure Registry
                command: |
                  export IMAGE_TAG=":3.1-ee"
                  export IMAGE1="graviteeio/apim-portal-ui"
                  export IMAGE="$IMAGE1$IMAGE_TAG"
                  echo "export IMAGE=$IMAGE" >> $BASH_ENV
                  echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
                  echo << parameters.version >>
            - when:
                  condition:
                      equal: [test, << parameters.version >>]
                  steps:
                      - docker-scan

workflows:
    pull_requests:
        jobs:
            - publish_prod_docker_images:
                 version: "test"
           
