version: 2.1

slack-fail-post-step: &slack-fail-post-step
  post-steps:
    - slack/notify:
        channel: 'devsecops'
        custom: |
          {
            "text": "",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "❌ *Failure* #${CIRCLE_JOB} `${CIRCLE_INTERNAL_TASK_DATA}` on `${CIRCLE_BRANCH}`"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "url": "${CIRCLE_BUILD_URL}"
                  }
                ]
              }
            ]
          }
        event: fail
slack-pass-post-step: &slack-pass-post-step
  post-steps:
    - slack/notify:
        channel: 'devsecops'
        custom: |
          {
            "text": "",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "✅ *Success* #${CIRCLE_JOB} `${CIRCLE_INTERNAL_TASK_DATA}` on `${CIRCLE_BRANCH}`"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "url": "${CIRCLE_BUILD_URL}"
                  }
                ]
              }
            ]
          }
        event: pass

orbs:
  slack: circleci/slack@4.1.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
      
    steps:
      - run:
          name: Success
          command: |
            exit 0
  last-job:
    docker:
      - image: cimg/base:stable
      
    steps:
      - run:
          name: Success
          command: |
            exit 0
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          #context: 
          #  - slack
          #<<: *slack-fail-post-step
          <<: *slack-pass-post-step
      - last-job:
          #context: [slack]
          requires:
            - build
          #<<: *slack-fail-post-step
          <<: *slack-pass-post-step

