version: 2.1
orbs:
    snyk: snyk/snyk@1.1.2
commands:
    docker-scan:
        steps:
            - run:
                name: Update image names
                command: |
                  export IMAGE="$IMAGE1:$IMAGE_TAG"
                  echo "export IMAGE=$IMAGE" >> $BASH_ENV
            - snyk/scan:
                organization: gravitee.io
                monitor-on-build: true
                severity-threshold: critical
                docker-image-name: ${IMAGE}
                fail-on-issues: false
                project: ${IMAGE_TAG}
        
jobs:
    publish_prod_docker_images:
        parameters:
            dry_run:
              type: boolean
              default: true
        docker:
            - image: cimg/base:stable
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Update image tags
                command: |
                  export IMAGE_TAG="3.1-ee"
                  export IMAGE1="graviteeio/apim-portal-ui"
                  echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
                  echo "export IMAGE1=$IMAGE1" >> $BASH_ENV
            - when:
                  condition:
                      equal: [false, << parameters.dry_run >>]
                  steps:
                      - docker-scan

workflows:
    pull_requests:
        jobs:
            - publish_prod_docker_images:
                 dry_run: false
           
