version: 2.1
orbs:
    snyk: snyk/snyk@1.1.2
commands:
    docker-scan:
        parameters:
            docker-image-name:
                type: string
                default: ""
                description: The name of the docker image to scan (without the version)
            version:
                  type: string
                  default: ""
                  description: Version of the docker image to scan    
        steps:
            - snyk/scan:
                organization: gravitee.io
                monitor-on-build: true
                severity-threshold: high
                docker-image-name: '<< parameters.docker-image-name >>:<< parameters.version >>'
                fail-on-issues: false
                project: << parameters.docker-image-name >>
        
jobs:
    publish_prod_docker_images:
        parameters:
            dry_run:
              type: boolean
              default: true
            enterprise_edition:
                default: false
                type: boolean
            graviteeio_version:
                default: "3.15-ee"
                type: string              
        docker:
            - image: cimg/base:stable
        steps:
            - when:
                  condition:
                      equal: [false, << parameters.dry_run >>]
                  steps:
                      - docker-scan:
                            docker-image-name: graviteeio/apim-management-api
                            version: << parameters.graviteeio_version >><<# parameters.enterprise_edition >>-ee<</ parameters.enterprise_edition >>
                            #echo << parameters.version >>

workflows:
    pull_requests:
        jobs:
            - publish_prod_docker_images:
                 dry_run: false
                 graviteeio_version: "3"
                 enterprise_edition: true
           
