version: 2.1
orbs:
    snyk: snyk/snyk@1.1.2
    slack: circleci/slack@4.8.1
commands:
    docker-scan:
        parameters:
            docker-image-name:
                type: string
                default: ""
                description: The name of the docker image to scan (without the version)
            version:
                type: string
                default: ""
                description: Version of the docker image to scan    
        steps:
          - run:
              name: install-nodesource-nodejs-snyk
              command: |     
                curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
                sudo apt install nodejs
                sudo npm install snyk -g                          
                snyk --help
                snyk auth $SNYK_TOKEN
          - run: # run snyk container monitor
              name: snyk container monitor
              command: |
                SLACK_MESSAGE1=<< parameters.docker-image-name >>:<< parameters.version >>
                SLACK_MESSAGE="${SLACK_MESSAGE1} image has been Tested for vulnerability using snyk and found issues"
                echo ${SLACK_MESSAGE}
                echo "export SLACK_MESSAGE='${SLACK_MESSAGE}'" >> $BASH_ENV              
                snyk config set disableSuggestions=true
                snyk container monitor << parameters.docker-image-name >>:<< parameters.version >> --app-vulns -d
                snyk container test << parameters.docker-image-name >>:<< parameters.version >> --app-vulns -d
                SLACK_MESSAGE="${SLACK_MESSAGE1} image has been Tested for vulnerability using snyk and no vulnerable paths found"
               
    notify-snyk-result:
      steps:
          - slack/notify:
                channel: 'devsecops'
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "```${SLACK_MESSAGE}```"
                       },
                       "accessory": {
                         "type": "button",
                         "text": {
                           "type": "plain_text",
                           "text": "Click here for scan details",
                           "emoji": true
                         },
                         "value": "click_me_123",
                         "url": "${CIRCLE_BUILD_URL}",
                         "action_id": "button-action"                    
                        }
                      }
                    ]
                  }
                event: always


jobs:       
    publish_prod_docker_images:
        parameters:
            dry_run:
                type: boolean
                default: true
            enterprise_edition:
                default: false
                type: boolean
            graviteeio_version:
                default: "3"
                type: string              
        docker:
            #- image: cimg/base:stable
            - image: cimg/openjdk:17.0.1
        steps:
            - when:
                  condition:
                      equal: [false, << parameters.dry_run >>]
                  steps:
                      - docker-scan:
                            docker-image-name: graviteeio/apim-management-ui
                            version: << parameters.graviteeio_version >><<# parameters.enterprise_edition >>-ee<</ parameters.enterprise_edition >>
            - notify-snyk-result     
workflows:
    pull_requests:
        jobs:
            - publish_prod_docker_images:
                 dry_run: false
                 graviteeio_version: "3.17.1"
                 enterprise_edition: true
           
