version: 2.1
orbs:
    slack: circleci/slack@4.8.1
    snyk: snyk/snyk@1.1.2
commands:  
    docker-scan:
      steps:
          - snyk/scan:
              organization: gravitee.io
              monitor-on-build: true
              severity-threshold: critical
              docker-image-name: graviteeio/apim-management-api:3.16.
              fail-on-issues: false  
              additional-arguments: --app-vulns
    notify-snyk-result: 
          parameters:
            CCI_STATUS:
              type: string
              default: "fail"
          steps:
            - when:
                condition: 
                  equal: ["pass", << parameters.CCI_STATUS >>]
                steps:        
                  - slack/notify:
                      channel: 'devsecops'
                      custom: |
                        {
                          "blocks": [
                            {
                              "type": "section",
                              "text": {
                                "type": "mrkdwn",
                                "text": "```${SLACK_MESSAGE}```"
                              },                        
                              "accessory": {
                                "type": "button",
                                "text": {
                                  "type": "plain_text",
                                  "text": "Click here for scan details",
                                  "emoji": true
                                },
                                "value": "click_me_123",
                                "url": "${CIRCLE_BUILD_URL}",
                                "action_id": "button-action"                    
                              }
                            }
                          ]
                        }

jobs:       
    publish_prod_docker_images: 
        parameters:
            tagb:
              type: env_var_name
              default: TAGANCH
        docker:
            - image: cimg/openjdk:17.0.1    
        steps:
            - docker-scan
workflows:
    pull_requests:
        jobs:
            - publish_prod_docker_images
            

           
